# Generated by Django 5.1 on 2024-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, null=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, null=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, null=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='simplemessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, null=True, to='admin_bot.replymarkup'),
        ),
    ]
