# Generated by Django 5.1 on 2024-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0002_alter_audiomessage_reply_markup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='num_at_position',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='num_at_position',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AddField(
            model_name='mapmessage',
            name='num_at_position',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AddField(
            model_name='simplemessage',
            name='num_at_position',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Порядковый номер в позиции'),
        ),
    ]
