# Generated by Django 5.1 on 2024-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0003_audiomessage_num_at_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='num_at_position',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='num_at_position',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='num_at_position',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, to='admin_bot.replymarkup'),
        ),
        migrations.AlterField(
            model_name='simplemessage',
            name='num_at_position',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер в позиции'),
        ),
        migrations.AlterField(
            model_name='simplemessage',
            name='reply_markup',
            field=models.ManyToManyField(blank=True, to='admin_bot.replymarkup'),
        ),
    ]
