# Generated by Django 5.1 on 2024-09-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0004_alter_audiomessage_num_at_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemessage',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_message', to='admin_bot.position'),
        ),
    ]
