# Generated by Django 5.1 on 2024-09-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0005_alter_simplemessage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_message', to='admin_bot.position'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_message', to='admin_bot.position'),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_message', to='admin_bot.position'),
        ),
    ]
